# Generated by Django 4.2.3 on 2023-07-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles/user-default.png', upload_to='profiles'),
        ),
    ]
