# Generated by Django 4.2.3 on 2023-07-06 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_editor_user_alter_professor_user_and_more'),
        ('account', '0004_alter_profile_image'),
    ]

    operations = [
    ]
