# Generated by Django 4.2.3 on 2023-07-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last_view',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
