# Generated by Django 4.2.3 on 2023-07-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_last_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='last_view',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='article',
            name='admin_last_view',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
