# Generated by Django 4.2.2 on 2023-07-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_judges'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification_Manager',
        ),
    ]
