# Generated by Django 4.2.3 on 2023-07-05 17:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_review_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
