# Generated by Django 4.2.3 on 2023-07-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_updated_review_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_view',
            field=models.DateTimeField(default=None),
        ),
    ]
