# Generated by Django 4.2.3 on 2023-07-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_last_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last_view',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
