# Generated by Django 4.2.3 on 2023-07-04 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_last_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='updated',
        ),
    ]
