# Generated by Django 4.2.3 on 2023-07-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_remove_article_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(default=False, null=True),
        ),
    ]
