# Generated by Django 4.2.3 on 2023-07-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_review_score'),
        ('articles', '0012_alter_review_body'),
    ]

    operations = [
    ]
